load("//bazel/rust:defs.bzl", "rust_library")

rust_library(
    name = "py",
    srcs = [
        "src/lib.rs",
        "src/pth.rs",
        "src/unpack.rs",
        "src/venv.rs",
    ],
    compile_data = [
        "src/_virtualenv.py",
        "src/activate.tmpl",
        "src/pyvenv.cfg.tmpl",
        "src/runfiles_interpreter.tmpl",
    ],
    visibility = [
        "//py/tools/unpack_bin:__pkg__",
        "//py/tools/venv_bin:__pkg__",
    ],
    deps = [
        "@rules_py_crates//:itertools",
        "@rules_py_crates//:miette",
        "@rules_py_crates//:pathdiff",
        "@rules_py_crates//:percent-encoding-2.3.1",
        "@rules_py_crates//:sha256",
        "@rules_py_crates//:tempfile",
        "@rules_py_crates//:thiserror",
        "@rules_py_crates//:uv-cache",
        "@rules_py_crates//:uv-distribution-filename",
        "@rules_py_crates//:uv-extract",
        "@rules_py_crates//:uv-install-wheel",
        "@rules_py_crates//:uv-pypi-types",
        "@rules_py_crates//:uv-python",
        "@rules_py_crates//:uv-virtualenv",
        "@rules_py_crates//:walkdir",
    ],
)
