load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("//py:defs.bzl", "py_binary")

package(default_visibility = [
    "//docs:__pkg__",
    "//uv/private:__subpackages__",
])

bzl_library(
    name = "rule",
    srcs = ["rule.bzl"],
    deps = ["@rules_python//python:defs_bzl"],
)

bzl_library(
    name = "defs",
    srcs = ["defs.bzl"],
    deps = [],
)

bzl_library(
    name = "repository",
    srcs = ["repository.bzl"],
    deps = [
        "//uv/private:parse_whl_name",
        "//uv/private/constraints/platform:defs",
    ],
)

py_binary(
    name = "extract_dist_info",
    srcs = ["extract_dist_info.py"],
    main = "extract_dist_info.py",
)
